package com.coliving.api.identity.domain.model

import java.time.Duration
import java.time.Instant
import java.util.UUID

/**
 * An opaque session token fulfilling RF-002.
 *
 * - The raw value is generated by the [com.coliving.api.identity.application.port.out.TokenGenerator]
 *   and returned to the client only once; only its cryptographic hash is persisted,
 *   so a database leak does not expose usable tokens.
 * - [deviceLabel] identifies the session/device, letting the user log out one
 *   device while keeping others (web + mobile).
 * - [expiresAt] bounds the session lifetime; [revokedAt] is set by logout
 *   (immediate revocation) or by an admin policy.
 */
class SessionToken(
    val id: UUID,
    val userId: UUID,
    val tokenHash: String,
    val deviceLabel: String,
    val createdAt: Instant,
    val expiresAt: Instant,
    revokedAt: Instant?,
) {
    var revokedAt: Instant? = revokedAt
        private set

    fun isActive(now: Instant): Boolean = revokedAt == null && !isExpired(now)

    fun isExpired(now: Instant): Boolean = !now.isBefore(expiresAt)

    fun revoke(now: Instant) {
        if (revokedAt == null) revokedAt = now
    }

    companion object {
        fun create(
            userId: UUID,
            tokenHash: String,
            deviceLabel: String,
            now: Instant,
            ttl: Duration,
        ): SessionToken = SessionToken(
            id = UUID.randomUUID(),
            userId = userId,
            tokenHash = tokenHash,
            deviceLabel = deviceLabel,
            createdAt = now,
            expiresAt = now.plus(ttl),
            revokedAt = null,
        )
    }
}